Importer
INF2A-Team-2/VisconSupportAPI pull request #20
Opened 2023-11-12 18:10 UTC by luuk180

2023-11-12 18:47 UTC, ZoutigeWolf requested changes
Je kan de route beter op /machines/import zetten

Je kan beter checken of een machine al bestaat voordat je een nieuwe maakt zodat je geen duplicates krijgt

2023-11-12 21:17 UTC, luuk180 commented
Ik heb je feedback verwerkt.

2023-11-12 21:37 UTC, ZoutigeWolf requested changes
Met die duplicates bedoel ik dat als 2 mensen dezelfde machine hebben dat ze dan ook dezelfde machine krijgen
Zoadat je niet in de machines table 2 machines hebt met de zelfde naam

2023-11-12 21:55 UTC, ZoutigeWolf commented
Je kan namelijk in de admin panel de machines per user aanpassen dus als je dan 2 dezelfde machines hebt dan zie je ook 2 dezelfde daar, is confusing

2023-11-12 22:02 UTC, luuk180 commented
Oh haha is al gefixt

2023-11-13 08:51 UTC, ZoutigeWolf approved these changes
Lgtm

2023-11-13 08:51 UTC, merged